name: Mi Primer Pipeline CI

on:
  push:
    branches: [ "main" ]

jobs:
  prueba-de-codigo:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo (Checkout)
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Ejecutar mi script
        run: python script.py
