name: Pipeline de Pruebas

on:
  push:
    branches: [ "main" ]

jobs:
  ejecutar-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el codigo
        uses: actions/checkout@v4

      - name: Preparar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Correr los tests
        run: python -m unittest tests.py
